### ISSUE TITLE
-f FILE

### ISSUE THREAD

**Issue by Freed-Wu** [wader/jqjq#17]
Can it support -f FILE?

**Comment by wader** [comment]
I think it could but it's a bit tricky as jq programs can't open files at runtime. But @thaliaarchi had an idea how it might work,  we could let the jqjq shell wrapper script call a argument parser helper thingy in jq code that figures out what arguments the "host" jq should be called with.

**Comment by thaliaarchi** [comment]
With that scheme, you'd have a two-line shell script. Your language stats would be perfect :).
```sh
#!/bin/sh
exec "$(jq -f cli.jq "$@")"
```
`cli.jq` would parse the arguments and produce a command invoking jq. It would need to produce the whole command, instead of just the arguments to jq, so that you could override the path to jq for using gojq, jaq, or another jq version.

**Comment by wader** [comment]
👍 yeap language stats is prio of course! 😄 so something like is probably what we want
